---
- name: Remove the user 'pi'
  user:
    name: pi
    state: absent
    remove: true

- name: Ensure a locale exists
  community.general.locale_gen:
    name: de_DE.UTF-8
    state: present

- name: install some convenient packages
  apt:
    name: ["neovim", "screenfetch", "iotop", "htop", "console-data"]
    state: present