---
- name: Creates SSH directory
  file:
    path: /root/.ssh/
    state: directory
    mode: 0755

- name: copy the ssh deployment key to the host
  copy:
    src: explorer_app-server-key
    dest: /root/.ssh/explorer_app-server-key
    owner: root
    group: root
    mode: 0600