---
- include_tasks: deploymentkey.yml

- name: Creates Project directory
  file:
    path: "{{ project_root }}"
    state: directory
    mode: 0755

- name: clone the project
  git:
    repo: 'git@github.com:christian-heusel/explorer-app.git'
    dest: "{{ project_root }}{{ project_name }}"
    key_file: /root/.ssh/explorer_app-server-key
    accept_hostkey: yes
    version: master
  register: git__project_checkout

- include_tasks: copy_initial_data.yml

- include_tasks: start_docker.yml
  when: git__project_checkout.changed

- include_tasks: setup_apache.yml