---
- name: install apache2
  apt:
    name: apache2
    state: present

- name: Enable the Apache2 module 
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http
    - proxy_balancer
    - lbmethod_byrequests
    - proxy_connect