---
- name: Check that the config files exist
  stat:
    path: "{{ project_root }}{{ project_name }}/server/{{ item }}"
  register: stat_result
  with_items:
    - "explorer_app-server_db.env"
    - "explorer_app-server.env"

- name: create the .env files, if they dont exist already
  copy:
    src: "{{ project_root }}{{ project_name }}/server/{{ item.name }}"
    dest: "{{ project_root }}{{ project_name }}/server/{{ item..name.split('.')[0] + '.' + item.name.split('.')[1] }}"
    remote_src: yes
    mode: 0600
  with_items:
    - "{{ stat_result.results }}"
  when: not item.stat.exists

- name: install docker-compose
  apt:
    name: docker-compose
    state: present

- name: build and start the docker image
  community.general.docker_compose:
    project_src: "{{ project_root }}{{ project_name }}"
    state: present
    build: yes
