---
version: '3.2'

services:
  explorer_app-server_db:
    image: postgres:13
    restart: always
    env_file:
      - server/explorer_app-server_db.env
    networks:
      - internal
    volumes:
      - db:/var/lib/postgresql/data

  explorer_app-server:
    build: server
    image: "explorer_app-server:latest"
    ports:
      - "127.0.0.1:3000:8081"
    restart: always
    env_file:
      - server/explorer_app-server.env
    networks:
      - internal
    volumes:
      - type: bind
        source: ./server/initial_data/
        target: /go/src/initial_data/
        read_only: true
    depends_on:
      - explorer_app-server_db

networks:
  internal: {}

volumes:
  db: {}
