---
# Interface to used for wifi.
interface_in: wlan0

# Interface for internet connection.
interface_out: eth0

# SSID / Name of network
ssid: explorer

# Wifi password.
passphrase: explorer

# Router IP
router_ip: 192.168.1.1

# Subnet
subnet_start: 192.168.1.10
subnet_end: 192.168.1.200

# Broadcast address
broadcast_address: 192.168.1.255

# Allow client Internet connection
# TODO: This is not yet respected!
allow_connection: False

wifi_country: DE
