// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Answer struct {
	ID                  int       `json:"ID"`
	StationNumber       int       `json:"station_number"`
	AnswerTime          time.Time `json:"answer_time"`
	SynchronizationTime time.Time `json:"synchronization_time"`
	ResultOption        *int      `json:"result_option"`
	ResultText          *string   `json:"result_text"`
	ResultNumber        *float64  `json:"result_number"`
}

type Device struct {
	AndroidID       string  `json:"android_id"`
	TeamID          int     `json:"team_id"`
	Brand           *string `json:"brand"`
	Model           *string `json:"model"`
	AndroidCodename *string `json:"android_codename"`
	AndroidRelease  *string `json:"android_release"`
}

type Station struct {
	StationNumber int     `json:"station_number"`
	Points        int     `json:"points"`
	StationType   int     `json:"station_type"`
	Coordinates   *string `json:"coordinates"`
	GridSquare    *string `json:"grid_square"`
	Title         *string `json:"Title"`
}

type Team struct {
	ID       int     `json:"ID"`
	Members  *int    `json:"members"`
	Authcode string  `json:"authcode"`
	Name     *string `json:"name"`
}
