---
# handlers file for ansible-wifi-router
- name: restart networking
  systemd:
    name: hostapd.service
    masked: no

- name: restart networking
  shell: ip addr flush dev {{ interface_in }}

- name: restart networking
  systemd:
    name: networking
    state: restarted
