targets:
  $default:
    builders:
      artemis:
        options:
          scalar_mapping:
            - custom_parser_import: 'lib/util/coercers.dart'
              graphql_type: Time
              dart_type: DateTime
          schema_mapping:
            - output: lib/api_gen/queries.graphql.dart
              schema: api/schema.graphql
              queries_glob: api/queries.graphql
    sources:
      - api/**.graphql
      - lib/**
      - $package$
      - api/schema.graphql