---
- name: remove the old container including its data
  community.general.docker_compose:
    project_src: "{{ project_root }}{{ project_name }}"
    state: absent
  listen: apply the new initial data

- name: set the initialize env var for the container
  lineinfile:
    path: "{{ project_root }}{{ project_name }}/server/explorer_app-server.env"
    state: absent
    regexp: '^FORCE_INITIALIZATION='
  listen: apply the new initial data

- name: start the docker containers with init env
  community.general.docker_compose:
    project_src: "{{ project_root }}{{ project_name }}"
    state: present
  listen: apply the new initial data

- name: stop the docker containers
  community.general.docker_compose:
    project_src: "{{ project_root }}{{ project_name }}"
    stopped: yes
  listen: apply the new initial data

- name: unset the initialize env var for the container
  lineinfile:
    path: "{{ project_root }}{{ project_name }}/server/explorer_app-server.env"
    line: "FORCE_INITIALIZATION=false"
  listen: apply the new initial data

- name: restart the docker container
  community.general.docker_compose:
    project_src: "{{ project_root }}{{ project_name }}"
    state: present
  listen: apply the new initial data