---
- name: general setup
  hosts: raspberrys
  roles:
    - usersetup

- name: docker setup
  hosts:
    - raspberrys
  vars:
    docker_apt_arch: armhf
    docker_install_compose: false
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - role: gantsign.oh-my-zsh
      users:
        - username: root
      oh_my_zsh_theme: geoffgarside

- name: project setup
  hosts:
    - server
    - raspberrys
  roles:
    - backend

- hosts:
    - raspberrys
  vars_files:
    - vars/apache.yml
  roles:
    - { role: geerlingguy.apache }

- hosts:
   - raspberrys
  roles:
   - ansible-wifi-router
