name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Vielen Dank für dein erstes Issue! :blush::fire:'' first issue'
        pr-message: 'Vielen Dank für deinen ersten PullRequest! :blush::fire:'' first pr'
